### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
import numpy as np

array_int = np.random.randint(1, 51, size=10)

print('Matriz de inteiros gerada:\n', array_int, end='\n\n')

print(f'Média: {np.mean(array)}')
print(f'Desvio Padrão: {np.std(array)}')


Matriz de inteiros gerada:
 [19 37 49 42  2 50  5 21 32 13]

Média: 0.674951788203727
Desvio Padrão: 0.1392157845165882


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)

print('Matriz original:\n', array, end='\n\n')

# Calula e atribui ao array a raiz aos valores menores ou iguais a 0,5
array[array <= 0.5] = np.sqrt(array[array <= 0.5])

print('Matriz com as raízes dos valores menores ou iguais a 0,5 da matriz original:\n' ,array)

Matriz original:
 [0.762827   0.65718409 0.66450772 0.32825349 0.61012573 0.65477183
 0.61252659 0.18404951 0.96809097 0.81753994]

Matriz com as raízes dos valores menores ou iguais a 0,5 da matriz original:
 [0.762827   0.65718409 0.66450772 0.57293411 0.61012573 0.65477183
 0.61252659 0.42900992 0.96809097 0.81753994]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)

print('Matriz 3D:\n', matriz, end='\n\n')

max_values = np.amax(matriz, axis=1)

print('Maiores valores da linha das matrizes 2D:\n', max_values)

Matriz 3D:
 [[[0.57628974 0.51746671 0.65653456]
  [0.45936346 0.13415654 0.92226862]
  [0.7884265  0.46762337 0.58375493]]

 [[0.8831821  0.76442071 0.72296678]
  [0.91664587 0.41105137 0.00930003]
  [0.94415706 0.90513101 0.52931222]]

 [[0.84214337 0.44695532 0.86079339]
  [0.57963212 0.93431539 0.51613082]
  [0.5069129  0.27957136 0.09169252]]]

Maiores valores da linha das matrizes 2D:
 [[0.7884265  0.51746671 0.92226862]
 [0.94415706 0.90513101 0.72296678]
 [0.84214337 0.93431539 0.86079339]]


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matrix = np.random.rand(5, 5)

print('Matriz gerada:\n', matrix, end='\n\n')

# Média de cada linha
media = np.mean(matrix, axis=1)
print('Média de cada linha: \n', media, end='\n\n')

# Subtrai os valores da linha pela a média de cada linha, utilizando o pivot da media
matrix_media_linha = matrix - media[:, np.newaxis]

print('Matriz subtraída pela média de cada linha:\n', matrix_media_linha)

Matriz gerada:
 [[0.43683708 0.78769365 0.090743   0.84929724 0.05663833]
 [0.18595257 0.923852   0.94665547 0.86393822 0.66956882]
 [0.86030034 0.3850849  0.02090885 0.67052606 0.85713125]
 [0.57938488 0.47228529 0.8207006  0.41150249 0.57624079]
 [0.31909801 0.87243773 0.51603158 0.51930844 0.39914503]]

Média de cada linha: 
 [0.44424186 0.71799342 0.55879028 0.57202281 0.52520416]

Matriz subtraída pela média de cada linha:
 [[-0.00740478  0.34345179 -0.35349886  0.40505538 -0.38760353]
 [-0.53204085  0.20585859  0.22866205  0.14594481 -0.04842459]
 [ 0.30151006 -0.17370538 -0.53788143  0.11173578  0.29834097]
 [ 0.00736207 -0.09973752  0.24867779 -0.16052032  0.00421798]
 [-0.20610615  0.34723358 -0.00917258 -0.00589572 -0.12605913]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)

# Seleciona a diagonal principal
diagonal_principal = np.diag(matriz)

# Seleciona a diagonal secundária
diagonal_secundaria = np.diag(np.fliplr(matriz))

#Calcula a média das diagonais
media_diagonais = np.mean([diagonal_principal, diagonal_secundaria])

#Calcula o desvio padrão das diagonais
dp_diagonais = np.std([diagonal_principal, diagonal_secundaria])

print('Matriz gerada:\n', matriz, end='\n\n')
print('Diagonal principal:\n', diagonal_principal, end='\n\n')
print('Diagonal secundária:\n', diagonal_secundaria, end='\n\n')
print('Média das diagonais:', media_diagonais, end='\n\n')
print('Desvio padrão das diagonais:', dp_diagonais)


Matriz gerada:
 [[0.19814787 0.87525991 0.35271191 0.87733969]
 [0.16507924 0.17136611 0.40617526 0.49977419]
 [0.25462663 0.89097316 0.86505519 0.82272255]
 [0.71296241 0.08080156 0.50417011 0.74799959]]

Diagonal principal:
 [0.19814787 0.17136611 0.86505519 0.74799959]

Diagonal secundária:
 [0.87733969 0.40617526 0.89097316 0.71296241]

Média das diagonais: 0.6087524106845477

Desvio padrão das diagonais: 0.2847517913476542
